version: "3"
services:
  pull_request_info_compile:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: pull_request_info_compile-image
    container_name: pull_request_info_compile-container
    tty: true
    env_file: .env # shellスクリプト内でも環境変数として使用するため
