name: get pull request info
on:
  push:
    branches:
      - master
jobs:
  get_pr_info:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: print github.event.head_commit.message
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: echo "$COMMIT_MESSAGE"
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute script
        env:
          GITHUB_REPOSITORY_NAME: ${{ github.repository}}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ATLASSIAN_EMAIL: ${{ secrets.ATLASSIAN_EMAIL }}
          ATLASSIAN_API_TOKEN: ${{ secrets.ATLASSIAN_API_TOKEN }}
          ATLASSIAN_URL: ${{ secrets.ATLASSIAN_URL }}
          JIRA_TARGET_PROJECT: ${{ secrets.JIRA_TARGET_PROJECT }}
          JIRA_TARGET_ISSUE_SUMMARY: 結合テスト観点
        run: |
          python get_pr_info.py
