name: get pull request info
on:
  push:
    branches:
      - master
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: print github.event.head_commit.message
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: echo "$COMMIT_MESSAGE"
      - name: execute script
        env:
          GITHUB_REPOSITORY_NAME: ${{ github.repository}}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python get_pr_info.py
